model:
  max_top_n: 10
  max_prior_token_length: 5
score:
  num_preds: 10

mlflow:
  local_tracking: False #If running on AML Comppute Instance, controls default experiments from populating during development

logging:
  version: 1
  disable_existing_loggers: False
  formatters:
    simple_formatter:
      format: "%(asctime)s %(levelname)-4s %(name)s: %(message)s"
      datefmt: "%Y-%m-%d %H:%M:%S"

  handlers:
    console_handler:
      class: logging.StreamHandler
      level: INFO
      formatter: simple_formatter

  root:
    handlers: [console_handler]
    level: INFO
    propagate: true

benchmark:
  model_compare_name: sequence_model_main
  conditions:
    - metric: "accuracy"
      condition: ">"
      benchmark: 0.1 # 10% accuracy benchmark