# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Definition of infra-related environment variables

variables:

  # DEV Environment
  # ENVIRONMENT: DEV
  # RESOURCE_GROUP: rg-MLOps-V2
  # LOCATION: eastus
  NAMESPACE: mlops
  PROJECTCODE: dstk
  VERSION: 0508
  # SERVICECONNECTION_RG: dstoolkit-mlops-v2-svc
  AMLWORKSPACE: mlw-$(NAMESPACE)-$(PROJECTCODE)-$(VERSION)
  STORAGEACCOUNT: staccaml$(NAMESPACE)$(PROJECTCODE)$(VERSION)
  KEYVAULT: akvaml$(NAMESPACE)$(PROJECTCODE)$(VERSION)
  APPINSIGHTS: aml-ai-$(NAMESPACE)-$(PROJECTCODE)-$(VERSION)
  CONTAINERREGISTRY: cr$(NAMESPACE)$(PROJECTCODE)$(VERSION)
  VIRTUALNETWORK: aml-vnet-$(NAMESPACE)
  PRIVATEDNSZONE: dnszone.api.azureml.ms
  PRIVATEDNSZONELINK: dnszonelink.api.azureml.ms
  PRIVATEDNSZONEGROUP: dzg$(NAMESPACE)$(PROJECTCODE)$(VERSION)
  PRIVATEENDPOINT: aml-pe-$(NAMESPACE)
  REQUIRESPRIVATEWORKSPACE: false
