name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.12
  - pip
  - pip:
    - pandas
    - scikit-learn>=1.3.0
    - mlflow>=2.9.2
    - azureml-mlflow>=1.53
    - azure-ai-ml>=1.10.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
