jobs:
- job: Build_Validation_Pipeline
  steps:
  - task: UsePythonVersion@0
    displayName: 'Use Python 3.9'
    inputs:
      versionSpec: '3.9'
      disableDownloadFromRegistry: true

  - task: Cache@2
    inputs:
      key: 'python_build_validate | "$(Agent.OS)" | .azure-pipelines/requirements/build_validation_requirements.txt'
      restoreKeys: |
        python_build_validate | "$(Agent.OS)"
      path: $(PIP_CACHE_DIR)
    displayName: 'Cache pip packages'

  - script: |
      python -m pip install --upgrade pip
      pip install -r .azure-pipelines/requirements/build_validation_requirements.txt --cache-dir $(PIP_CACHE_DIR)
    displayName: "Load Python Dependencies"

  - script: |
      flake8 .
    displayName: "Lint with flake8"
    enabled: true

  - script: |
      pytest --junitxml=junit/test-results.xml --cov=. --cov-report=xml
    displayName: 'Run Unit Tests'
    condition: succeededOrFailed()

  - task: PublishTestResults@2
    condition: succeededOrFailed()
    inputs:
      testResultsFiles: '**/test-*.xml'
      testRunTitle: 'Publish Test Results for Python $(python.version)'

  - task: PublishCodeCoverageResults@1
    inputs:
      codeCoverageTool: Cobertura
      summaryFileLocation: '$(System.DefaultWorkingDirectory)/**/coverage.xml'