# Azure ML configuration.
aml_config:
  subscription_id: ${SUBSCRIPTION_ID}
  resource_group_name: ${RESOURCE_GROUP_NAME}
  workspace_name: ${WORKSPACE_NAME}

environment_configuration:
  env_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
  build_reference: ${BUILD_BUILDID}

pipeline_configs:
  london_taxi_pr:
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    conda_path: mlops/london_taxi/environment/conda.yml
    aml_env_name: london_env
    dataset_name: london_taxi_pr_data

  sequence_model_pr:
    cluster_region: eastus2
    cluster_size: STANDARD_DS3_V2
    cluster_name: cpucluster
    conda_path: mlops/sequence_model/environment/conda.yml
    aml_env_name: sequence-model
    dataset_uri_folder: sequence_model_data
    model_type: sequence_model
    allow_synthetic_fallback: true
    synthetic_data_config:
      num_sequences: 100
      sequence_length: 20

  docker_taxi_pr:
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    dockerfile_path: Dockerfile
    docker_context_path: mlops/docker_taxi/environment
    aml_env_name: docker_taxi_env
    dataset_name: docker_taxi_pr_data

  london_taxi_dev:
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    conda_path: mlops/london_taxi/environment/conda.yml
    aml_env_name: london_env
    dataset_name: london_taxi_pr_data

  sequence_model_dev:
    cluster_region: eastus2
    cluster_size: STANDARD_DS3_V2
    cluster_name: cpucluster
    conda_path: mlops/sequence_model/environment/conda.yml
    aml_env_name: sequence-model
    dataset_uri_folder: sequence_model_data
    model_type: sequence_model
    allow_synthetic_fallback: true
    synthetic_data_config:
      num_sequences: 100
      sequence_length: 20

  docker_taxi_dev:
    cluster_region: eastus
    cluster_size: STANDARD_DS3_v2
    cluster_name: cpucluster
    dockerfile_path: Dockerfile
    docker_context_path: mlops/docker_taxi/environment
    aml_env_name: docker_taxi_env
    dataset_name: docker_taxi_pr_data

deployment_configs:
    london_taxi_batch_pr:
      score_file_name: score.py
      score_dir: model/london_taxi/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      deployment_conda_path: model/london_taxi/batch_environment/conda.yml
      endpoint_name: london-taxi-be-pr-000
      endpoint_desc: A batch endpoint serving an MLflow model for online taxi (PR)
      deployment_name: london-taxi-bd-pr-000
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      mini_batch_size: 10
      output_file_name: predictions.csv
      max_retries: 3
      retry_timeout: 300
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_desc: A batch deployment for PR environment
      test_dataset_name: london_taxi_batch_test

    london_taxi_online_pr:
      score_file_name: score.py
      test_file_path: model/london_taxi/online_test_data/sample-request.json
      endpoint_name: london-taxi-rte-pr-001
      endpoint_desc: An online endpoint serving an MLflow model for online taxi (PR)
      deployment_desc:
      deployment_name: london-taxi-rtd-pr-001
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/london_taxi/online_environment/conda.yml
      score_dir: model/london_taxi/online
      deployment_instance_count: 1

    sequence_model_batch_pr:
      score_file_name: score.py
      score_dir: model/sequence_model/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      max_retries: 3
      retry_timeout: 1800
      deployment_conda_path: model/sequence_model/batch_environment/conda.yml
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      endpoint_name: seq-model-be-pr-004
      endpoint_desc: A batch endpoint serving a custom model for the sequence model (PR)
      deployment_name: seq-model-bd-pr-004
      test_dataset_name: sequence_model_batch_test
      mini_batch_size: 10
      output_file_name: predictions.csv

    sequence_model_online_pr:
      score_file_name: score.py
      test_file_path: model/sequence_model/online_test_data/sample-request.json
      endpoint_name: seq-model-rte-pr-005
      endpoint_desc: An online endpoint serving a custom model for the sequence model (PR)
      deployment_desc:
      deployment_name: seq-model-rtd-pr-005
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/sequence_model/online_environment/conda.yml
      score_dir: model/sequence_model/online
      deployment_instance_count: 1

    docker_taxi_batch_pr:
      score_file_name: score.py
      score_dir: model/docker_taxi/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      deployment_conda_path: model/docker_taxi/batch_environment/conda.yml
      endpoint_name: docker-taxi-be-pr-002
      endpoint_desc: A batch endpoint serving an MLflow model for docker taxi (PR)
      deployment_name: docker-taxi-bd-pr-002
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      mini_batch_size: 10
      output_file_name: predictions.csv
      max_retries: 3
      retry_timeout: 1800
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_desc: A batch deployment for PR environment
      test_dataset_name: docker_taxi_batch_test

    docker_taxi_online_pr:
      score_file_name: score.py
      test_file_path: model/docker_taxi/online_test_data/sample-request.json
      endpoint_name: docker-taxi-rte-pr-003
      endpoint_desc: An online endpoint serving an MLflow model for docker taxi (PR)
      deployment_desc:
      deployment_name: docker-taxi-rtd-pr-003
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/docker_taxi/online_environment/conda.yml
      score_dir: model/docker_taxi/online
      deployment_instance_count: 1

    london_taxi_batch_dev:
      score_file_name: score.py
      score_dir: model/london_taxi/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      deployment_conda_path: model/london_taxi/batch_environment/conda.yml
      endpoint_name: london-taxi-be-000
      endpoint_desc: A batch endpoint serving an MLflow model for online taxi
      deployment_name: london-taxi-bd-000
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      mini_batch_size: 10
      output_file_name: predictions.csv
      max_retries: 3
      retry_timeout: 300
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_desc: A batch deployment
      test_dataset_name: london_taxi_batch_test

    london_taxi_online_dev:
      score_file_name: score.py
      test_file_path: model/london_taxi/online_test_data/sample-request.json
      endpoint_name: london-taxi-rte-001
      endpoint_desc: An online endpoint serving an MLflow model for online taxi
      deployment_desc:
      deployment_name: london-taxi-rtd-001
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/london_taxi/online_environment/conda.yml
      score_dir: model/london_taxi/online
      deployment_instance_count: 1

    sequence_model_batch_dev:
      score_file_name: score.py
      score_dir: model/sequence_model/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      max_retries: 3
      retry_timeout: 1800
      deployment_conda_path: model/sequence_model/batch_environment/conda.yml
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      endpoint_name: seq-model-be-004
      endpoint_desc: A batch endpoint serving a custom model for the sequence model
      deployment_name: seq-model-bd-004
      test_dataset_name: sequence_model_batch_test
      mini_batch_size: 10
      output_file_name: predictions.csv

    docker_taxi_batch_dev:
      score_file_name: score.py
      score_dir: model/docker_taxi/batch
      batch_cluster_name: batchcluster
      batch_cluster_region: eastus
      batch_cluster_size: STANDARD_DS3_v2
      deployment_conda_path: model/docker_taxi/batch_environment/conda.yml
      endpoint_name: docker-taxi-be-002
      endpoint_desc: A batch endpoint serving an MLflow model for docker taxi
      deployment_name: docker-taxi-bd-002
      cluster_instance_count: 1
      max_concurrency_per_instance: 1
      mini_batch_size: 10
      output_file_name: predictions.csv
      max_retries: 3
      retry_timeout: 1800
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_desc: A batch deployment
      test_dataset_name: docker_taxi_batch_test

    sequence_model_online_dev:
      score_file_name: score.py
      test_file_path: model/sequence_model/online_test_data/sample-request.json
      endpoint_name: seq-model-rte-005
      endpoint_desc: An online endpoint serving a custom model for the sequence model
      deployment_desc:
      deployment_name: seq-model-rtd-005
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/sequence_model/online_environment/conda.yml
      score_dir: model/sequence_model/online
      deployment_instance_count: 1

    docker_taxi_online_dev:
      score_file_name: score.py
      test_file_path: model/docker_taxi/online_test_data/sample-request.json
      endpoint_name: docker-taxi-rte-003
      endpoint_desc: An online endpoint serving an MLflow model for docker taxi
      deployment_desc:
      deployment_name: docker-taxi-rtd-003
      deployment_traffic_allocation: 100
      deployment_vm_size: Standard_F4s_v2
      deployment_base_image: mcr.microsoft.com/azureml/openmpi4.1.0-ubuntu22.04
      deployment_conda_path: model/docker_taxi/online_environment/conda.yml
      score_dir: model/docker_taxi/online
      deployment_instance_count: 1
