name: prs-env
channels:
  - conda-forge
dependencies:
  - python=3.9
  - pip
  - pip:
    - pandas
    - numpy==1.23.5
    - scikit-learn==1.3.2
    - mlflow>=2.9.2
    - azureml-mlflow>=1.53
    - azure-ai-ml>=1.10.0
    - azure-identity>=1.15.0
    - azure-keyvault-secrets>=4.7.0
    - azureml-inference-server-http
    - Werkzeug==2.3.8
