# Copyright (c) Microsoft Corporation. All rights reserved.
# Licensed under the MIT License.

# Pipeline that deploys the infrastructure and sets up compute & data in the AML workspace

trigger:
- none

pr:
  branches:
    include:
    - main
    - develop

  paths:
    include:
    - infra/bicep
  
variables:
- template: /infra/bicep/configuration/configuration-infra-DEV.variables.yml

pool:
  vmImage: 'ubuntu latest'

stages:

####################
##  DEPLOY INFRA  ##
####################

# Deploy DEV Environment
- stage: deployinfra_dev
  displayName: 'Deploy DEV Environment'
  jobs:
  - template: /infra/bicep/templates/deploy-env-infra.template.yml
    parameters:
      environmentName: $(ENVIRONMENT)
      azureMgrConnection: $(SERVICECONNECTION_RG)
      resourceGroup: $(RESOURCE_GROUP)
      location: $(LOCATION)
      variablesTemplateBase: '${{variables.template}}'
      storageAccount: $(STORAGEACCOUNT)
      keyVaultName: $(KEYVAULT)
      appInsightsName: $(APPINSIGHTS)
      containerRegistryName: $(CONTAINERREGISTRY)
      amlWorkspaceName: $(AMLWORKSPACE)
      virtualNetworkName: $(VIRTUALNETWORK)
      privateDnsZoneName: $(PRIVATEDNSZONE)
      privateDnsZoneLinkName: $(PRIVATEDNSZONELINK)
      privateDnsZoneGroupName: $(PRIVATEDNSZONEGROUP)
      privateEndpointName: $(PRIVATEENDPOINT)
      requiresPrivateWorkspace: $(REQUIRESPRIVATEWORKSPACE)
