FROM mcr.microsoft.com/azureml/minimal-ubuntu20.04-py38-cpu-inference:latest

ARG model_folder
ARG model_registered_name
ARG model_file_name
ARG score_file 

ENV MODEL_FILE_NAME=$model_file_name
ENV MODEL_LOG_PATH=/var/azureml-app/logs/
ENV MODEL_NAME=$model_registered_name

COPY environment/requirements.txt ./requirements.txt

RUN  pip install -r ./requirements.txt

RUN mkdir -p /var/azureml-app/azureml-models
RUN mkdir -p /var/azureml-app/logs/
# score file
COPY scoring/$score_file /var/azureml-app/$score_file
ENV AZUREML_ENTRY_SCRIPT=$score_file

# Model
COPY $model_registered_name/$model_file_name /var/azureml-app/azureml-models/$model_file_name
ENV AZUREML_MODEL_DIR=/var/azureml-app/azureml-models

CMD ["runsvdir","/var/runit"]