name: Install Workflow Requirements

description: Installs the required python packages for the workflow.

inputs:
  versionSpec:
    description: "The Python version to use in the environment."
    default: "3.9"
  arm_client_id:
    description: "client id of service principal used to authenticate with azure"
    required: true
  arm_tenant_id:
    description: "client id of service principal used to authenticate with azure"
    required: true    
  subscription_id:
    description: "client id of service principal used to authenticate with azure"
    required: true 

runs:
  using: composite
  steps:
    - name: Azure login
      uses: azure/login@v2
      with:
        client-id: ${{ inputs.arm_client_id }}
        tenant-id: ${{ inputs.arm_tenant_id }}
        subscription-id: ${{ inputs.subscription_id }}

    - uses: actions/setup-python@v5
      with:
        python-version: ${{ inputs.versionSpec }}

    - name: Load Python Dependencies
      shell: bash
      run: |
        python -m pip install --upgrade pip
        python -m pip install --upgrade -r .github/requirements/execute_job_requirements.txt