pr: none
trigger:
  branches:
   include:
     - main
  paths:
    include:
      - .azure-pipelines/*
      - mlops/common/*
      - mlops/london_taxi/*
      - src/london_src/*
      - model/london_taxi/*
      - src/shared/*

pool:
  vmImage: ubuntu-latest


variables:
- group: mlops_platform_dev_vg
- name: PIP_CACHE_DIR
  value: $(Pipeline.Workspace)/.pip/configure_agent

parameters:
 - name: env_name
   displayName: "Execution Environment"
   default: "dev"
 - name: model_type
   displayName: "model type"
   default: "london_taxi"

stages:
  - template: templates/platform_cd_pipeline.yml
    parameters:
      exec_environment: ${{ parameters.env_name }}
      model_type: ${{ parameters.model_type }}
