name: Manual CI Dispatch

on:
  workflow_dispatch:
    inputs:
      exec_environment:
        type: string
        description: "Execution environment"
        required: false
        default: "pr"
      model_type:
        type: string
        description: "Model type to run (e.g., nyc_taxi, london_taxi, docker_taxi, sequence_model)"
        required: false
        default: "london_taxi"
      is_docker:
          type: boolean
          description: "Is Docker used for build validation?"
          required: true
          default: false

permissions:
  id-token: write
  contents: read

jobs:
  run-ci:
    uses: ./.github/workflows/platform_ci_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'ci' }}
      model_type: ${{ inputs.model_type || 'nyc_taxi' }}
      is_docker: ${{ inputs.is_docker }}
