name: Custom Object Detection CD Workflow

on:
  push:
    branches:
      - main
    paths:
      - mlops/common/**
      - mlops/docker_taxi/**
      - model/docker_taxi/**
      - src/docker_taxi_src/**
      - test/docker_taxi/**
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "dev"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "docker_taxi"
permissions:
  id-token: write
  contents: read          
jobs:
  run-cd-workflow:
    uses: ./.github/workflows/platform_cd_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'dev' }}
      model_type: ${{ inputs.model_type || 'docker_taxi' }}
