name: Platform CI Workflow

on:
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "Execution Environment"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "type of model to execute"
        required: true
      is_docker:
          type: boolean
          description: "Is Docker used for build validation?"
          required: false
          default: false
env:
  SUBSCRIPTION_ID: ${{vars.SUBSCRIPTION_ID}}
  RESOURCE_GROUP_NAME: ${{ vars.RESOURCE_GROUP_NAME }}
  WORKSPACE_NAME: ${{ vars.WORKSPACE_NAME }}
  ARM_CLIENT_ID: ${{vars.ARM_CLIENT_ID}}
  ARM_TENANT_ID: ${{vars.ARM_TENANT_ID}}
  BUILD_BUILDID: ${{ github.run_id }}
  BUILD_SOURCEBRANCHNAME: ${{ github.head_ref || github.ref_name }}          
jobs:
  build-validation:
    name: Build Validation
    uses: ./.github/workflows/build_validation_workflow.yml
    with:
      image_name: ${{ inputs.exec_environment }}
      model_type: ${{ inputs.model_type }}
      is_docker: ${{ inputs.is_docker }}
      
  execute-ml-job-pipeline:
    name: Execute ML Job Pipeline
    runs-on: ubuntu-latest
    needs: build-validation
    steps:
      - name: Checkout Actions
        uses: actions/checkout@v1
      - name: Configure Azure ML Agent
        uses: ./.github/actions/configure_azureml_agent
    
      - name: Execute AzureML Pipeline
        uses: ./.github/actions/execute_shell_code
        with:
            arm_client_id: ${{ env.ARM_CLIENT_ID }}
            arm_tenant_id: ${{ env.ARM_TENANT_ID }}
            subscription_id: ${{ env.SUBSCRIPTION_ID }}
            script_parameter: |
                python -m mlops.${{ inputs.model_type }}.src.mlops_pipeline \
                    --build_environment ${{ inputs.exec_environment }} \
                    --wait_for_completion True
