name: Sequence Model PR Workflow

on:
  pull_request:
    branches:
      - main
    paths:
      - '.github/**'
      - 'mlops/common/**'
      - 'mlops/sequence_model/**'
      - 'model/sequence_model/**'
      - 'src/sequence_model/**'
      - 'test/sequence_model/**'
  workflow_call:
    inputs:
      exec_environment:
        type: string
        description: "The environment to run the workflow in"
        required: true
        default: "pr"
      model_type:
        type: string
        description: "The type of model to run the workflow for"
        required: true
        default: "sequence_model"
permissions:
  id-token: write
  contents: read    
jobs:
  run-pr-workflow:
    uses: ./.github/workflows/platform_pr_workflow.yml
    with:
      exec_environment: ${{ inputs.exec_environment || 'pr' }}
      model_type: ${{ inputs.model_type || 'sequence_model' }}
      